import pyautogui
import time

i = input("Search: ")

pyautogui.moveTo(466,1055)
time.sleep(0.2)
pyautogui.click()
time.sleep(0.7)
pyautogui.moveTo(384,58)
time.sleep(0.2)
pyautogui.click()
time.sleep(0.2)
pyautogui.write("youtube.com")
time.sleep(0.2)
pyautogui.press("enter")
time.sleep(0.2)
pyautogui.moveTo(843,148)
time.sleep(0.2)
pyautogui.click()
time.sleep(0.2)
pyautogui.write(i)
time.sleep(0.2)
pyautogui.press("enter")
time.sleep(0.9)
pyautogui.moveTo(668,361)
time.sleep(0.2)
pyautogui.click()
time.sleep(0.5)
pyautogui.press("f")
time.sleep(0.2)